/**
 * LinkedIn posts feed for the portfolio "Posts" section.
 * Synced from https://www.linkedin.com/in/kazitonu/recent-activity/all/
 * Images are self-hosted under public/posts/ so they never expire.
 * This file is regenerated by the daily LinkedIn-posts sync job.
 */

export interface LinkedInPost {
  id: string;
  text: string;
  image: string;
  /** ISO date, e.g. "2026-10-05" */
  date: string;
  reactions: number | null;
  comments: number | null;
  url: string;
}

/** ISO date of the last sync, e.g. "2026-10-05" */
export const postsUpdatedAt = "2026-10-08";

export const linkedinPosts: LinkedInPost[] = [
  {
    id: "7513705567450828800",
    text: `WHAT'S INSIDE THAT MANHOLE CAN KILL YOU IN 60 SECONDS.

A confined space kills without warning — no fire, no smoke, no sound. Oxygen drops below 19.5% and a worker simply falls asleep… and never wakes up. In Singapore, manhole entry is one of the most tightly controlled works under WSH rules — for a reason.

The 5 silent killers inside a confined space:

☠️ Oxygen too low (below 19.5%) or too high (above 23.5%) — both are deadly
☠️ Hydrogen sulphide (H2S) — the rotten-egg smell disappears at high concentrations as your nose goes numb
☠️ Flammable gas — keep it below 10% LEL, or one spark is enough
☠️ Engulfment — water, sludge or sand can bury you in seconds
☠️ Carbon monoxide — colourless, odourless, kills silently

Before ANYONE goes in:

✅ Valid confined space entry permit — no permit, no entry, no excuse
✅ Gas test done and logged BEFORE entry — then continuous monitoring while inside
✅ Standby man outside, eyes on the entrant at all times, with a radio
✅ Mechanical ventilation running — never trust natural ventilation alone
✅ Rescue tripod and retrieval line ready — most confined space deaths are would-be rescuers. Never go in after someone without breathing apparatus.

👉 Simple safety rule: Test before you enter. Ventilate while you work. Watch while your buddy is inside.

❓ QUIZ FOR YOU: You arrive on site and see a worker lowering himself into a manhole. The gas meter is still in the toolbox, untouched. What is YOUR first action? Tell me below. 👇

#WSH #SafetyCoordinator #SingaporeConstruction #ConfinedSpace #WorkplaceSafety #SafetyFirst #ConstructionSafety #ToolboxTalk`,
    image: "/posts/post-12.jpg",
    date: "2026-10-08",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7513705567450828800",
  },
  {
    id: "7513346293147213824",
    text: `A wrench left on a scaffold edge is a loaded weapon.
A 1 kg spanner dropped from 10 metres hits the ground at 50 km/h — faster than a cyclist at full sprint. Your hard hat is rated for small falling objects, not for that. 🏗️

Most dropped-object incidents are not freak accidents. They are somebody's tool, somebody's phone, somebody's bolt:

🧰 Tether your tools — every tool used above a work area gets a lanyard, no exceptions
🧱 Fit toe boards on every scaffold platform — a 15 cm board stops the tool before it becomes a missile
🚧 Barricade the drop zone below — if nobody stands under it, nobody gets hit by it
🪖 Wear your hard hat with the chin strap fastened — a hat on the ground protects nobody
👀 Do a 2-minute housekeeping sweep before every break and at end of shift — loose items on ledges are tomorrow's incidents

👉 Simple safety rule: If it is not tethered, tied down, or put away — it is a falling object waiting to happen.

❓ QUIZ FOR YOU: A worker is bolting steel on level 5. His hammer is untethered and there is no toe board. What is YOUR first action — stop him, or tell him to finish fast? Tell me below. 👇

#WSH #SafetyCoordinator #SingaporeConstruction #DroppedObjects #StruckBySafety #ConstructionSafety #SafetyFirst`,
    image: "/posts/post-11.jpg",
    date: "2026-10-07",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7513346293147213824",
  },
  {
    id: "7512987136061550592",
    text: `A suspended load never gives you a second chance. A concrete panel looks calm hanging from a crane hook — until a sling slips, a shackle cracks, or the ground under the crane gives way. Then 2 tonnes of concrete falls in less than one second. 🏗️
Most crane accidents on site do not come from the crane breaking. They come from what we do under the hook:
🏗️ Never walk or stand under a suspended load — this one rule saves more lives than any gadget
🏗️ Watch your sling angle: at 60° you keep 87% of the sling's capacity, at 45° only 71%, and at 30° it drops to 50% — the sharper the angle, the weaker the lift
🏗️ Check the ground: outriggers must sit on firm, level ground with proper mats — soft or uneven ground is one of the most common causes of crane overturn
🏗️ One trained signalman gives the signals — everyone else stays clear of the lifting zone, at least 3 metres from the load path
🏗️ Inspect every sling, hook and shackle before each lift — cut slings, cracked hooks and bent shackles go to the bin, not back on the rack
👉 Simple safety rule: If the load can fall on you, you are standing in the wrong place.
❓ QUIZ FOR YOU: A 2-tonne sling is rigged at a sharp 30° angle to lift a 1-tonne load. Safe or not safe? Tell me below. 👇
#WSH #SafetyCoordinator #SingaporeConstruction #CraneSafety #LiftingSafety #ConstructionSafety #SafetyFirst`,
    image: "/posts/post-10.jpg",
    date: "2026-10-06",
    reactions: null,
    comments: 1,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7512987136061550592",
  },
  {
    id: "7512627460472102912",
    text: `Electricity is the quietest killer on a construction site.
No noise. No warning. One touch of a live cable can be enough. ⚡
Most electrical accidents on site do not come from big machines.
They come from small things we walk past every day:
🔌 Cables lying on wet ground — water plus damaged insulation can carry 230 volts straight through you
🔌 No 30mA RCD protection — a proper residual current device trips in under 0.2 seconds, fast enough to save a life
🔌 Taped-up plugs and cracked extension leads — tape is not a repair, it is a trap
🔌 Switchboards with no lockout — live panels must be locked and tagged, no shortcuts
🔌 No test-before-touch — always prove the circuit is dead with a tested voltage tester
👉 Simple safety rule: If it is plugged in, treat it as LIVE until you prove it is dead.
❓ QUIZ FOR YOU: You see a worker drilling in the rain, extension cable lying in a puddle. What is YOUR first action — stop him, or tell him to finish fast? Tell me below. 👇
#WSH #SafetyCoordinator #SingaporeConstruction #ElectricalSafety #ConstructionSafety #SafetyFirst`,
    image: "/posts/post-1.jpg",
    date: "2026-10-05",
    reactions: 1,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7512627460472102912",
  },
  {
    id: "7512258149916209152",
    text: `In a fire, most people do not die from the flames.
They die from the smoke. 💨
Hot toxic smoke can fill a stairwell in minutes. Just a few breaths can make a worker lose their way, collapse — and never get out.
On a construction site, one blocked exit can turn a small fire into a tragedy:
🚨 Keep exit routes clear at ALL times — no boxes, materials or bikes blocking the way
🚨 Every exit door must open freely — a locked door steals seconds that people may not have
🚨 Make sure exit signs and emergency lights work — smoke takes away your vision fast
🚨 Do evacuation drills regularly — everyone must know their route BEFORE the emergency
🚨 Head straight to the assembly point — never go back inside for tools or belongings
👉 Simple safety rule: If you cannot walk out of your workplace in 60 seconds, something is wrong.
When was the last time you walked your site's emergency exit route? Be honest — tell me in the comments. 👇
#WSH #SafetyCoordinator #SingaporeConstruction #FireSafety #EmergencyPreparedness #ConstructionSafety`,
    image: "/posts/post-2.jpg",
    date: "2026-10-04",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7512258149916209152",
  },
  {
    id: "7511894177861791744",
    text: `Every year, falls from height are the number one killer on construction sites in Singapore. 😔
And many of these falls start on a badly built scaffold.

Before you step onto any scaffold today, check these 5 points:

1️⃣ Inspection tag — every scaffold must be inspected at least every 7 days. No valid tag on the scaffold, no climb.
2️⃣ Guardrails — top rail at 1 metre, mid rail, and toe boards at least 150 mm high. Missing rails means missing protection.
3️⃣ Base and foundation — every standard must stand on a base plate and sole board, on firm and level ground. No bricks, no hollow blocks.
4️⃣ Tied to the structure — a scaffold must be tied to the building at regular intervals. A free-standing tall scaffold can collapse in strong wind.
5️⃣ Safe access — use a secured ladder that extends 1 metre above the platform. Never climb the scaffold frame itself.

⛔ MY RULE: If the scaffold has no valid inspection tag, I stop the work. No tag, no go.

👇 QUIZ FOR YOU: You walk onto a site and see workers on a scaffold with no inspection tag. The foreman says "it was checked last month." What do YOU do — stop the work, or let it continue? Comment your answer below! 💬

#WSH #SafetyCoordinator #SingaporeConstruction #ScaffoldSafety #WorkAtHeight #ConstructionSafety #FallProtection #SafetyFirst`,
    image: "/posts/post-3.jpg",
    date: "2026-10-03",
    reactions: 1,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7511894177861791744",
  },
  {
    id: "7511693062805413888",
    text: `Gravity doesn't take breaks, and neither should our focus. A fall from just 2 meters can be fatal or life-altering—yet it remains one of the most common risks on our sites every single day.
To make sure everyone goes home safely to their families, we have to get the basics right before our feet leave the ground:
Inspect your gear daily: Check your full-body harness and lanyards for any fraying, rust, or stiffness before every single shift. If in doubt, swap it out.
Secure the edges: Ensure all temporary edge protection is fully secured, with rigid top rails positioned exactly 1 meter above the walking surface.
Maintain 100% tie-off: Use a twin-tail lanyard system. Never detach your first hook until your second hook is safely secured to the next anchor point.
Calculate fall clearance: Always ensure you have a safe fall clearance distance—typically at least 5 meters below the anchor point—so your gear can actually do its job before you hit the level below.
Never take a shortcut when working at height. Look out for your team, and speak up immediately if a barricade or lifeline looks loose.
What is the very first thing you check on your personal fall arrest gear before starting a height job?
#WSH #SafetyCoordinator #SingaporeConstruction #WorkAtHeight #SafetyCulture #ConstructionSafety #ZeroHarm`,
    image: "/posts/post-4.jpg",
    date: "2026-10-02",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7511693062805413888",
  },
  {
    id: "7511590885462241280",
    text: `Pedestrians and heavy construction vehicles should never mix. Segregation is the only foolproof line of defense.
Managing vehicular traffic on dynamic sites requires absolute separation of paths:
* Physical Segregation: Use rigid guardrails or interlocking barriers—not just caution tape—to separate pedestrian walkways from plant routes.
* Designated Crossing Points: Install marked crosswalks with convex mirrors and clear sightlines at high-traffic intersections.
* Appointed Traffic Marshals: Ensure competent banksmen oversee heavy vehicle maneuvering, reversing, and gate crossings.
* Speed & Reversing Limits: Enforce strict site speed limits and minimize reversing maneuvers through one-way site flow designs.
When people and plant share space, physical barriers save lives.
#TrafficManagement #SiteLogistics #PlantAndPedestrian #WSH #CivilEngineering #SiteSafety #SingaporeSafety`,
    image: "/posts/post-5.jpg",
    date: "2026-10-02",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7511590885462241280",
  },
  {
    id: "7511228884252610560",
    text: `Noise-Induced Deafness (NID) is irreversible, permanent, and completely preventable.
On active construction sites, loud tools degrade hearing gradually—until speech and life sounds become muffled:
* Hierarchy of Control: Enclose noisy compressors, use quieter methods where feasible, or install acoustic screening blankets.
* Hearing Protection Zones: Clearly demarcate areas exceeding 85 dBA and enforce mandatory earplugs or earmuffs.
* Proper Fit & Maintenance: Ensure foam earplugs are rolled thin, inserted properly into the ear canal, and allowed to expand fully.
* Audiometric Screening: Keep up with annual hearing tests for noise-exposed workers to catch early threshold shifts before severe damage occurs.
Protect your hearing today so you can enjoy conversations tomorrow.
#HearingConservation #NoiseInducedDeafness #OccupationalHealth #IndustrialHygiene #WSHCoordinator #PPECompliance #SingaporeBuilders`,
    image: "/posts/post-6.jpg",
    date: "2026-10-01",
    reactions: null,
    comments: null,
    url: "https://www.linkedin.com/feed/update/urn:li:activity/7511228884252610560",
  },
];
